---
abstract: 'Generate canonical perlcritic.rc files from reduced configuration'
author:
  - 'Kent Fredric <kentfredric@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Spec::Functions: '0'
  List::Util: '0'
  Test::More: '0.89'
  version: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.012, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Perl-Critic-ProfileCompiler
provides:
  Perl::Critic::ProfileCompiler:
    file: lib/Perl/Critic/ProfileCompiler.pm
    version: '0.001000'
  Perl::Critic::ProfileCompiler::Action::add_or_append_plugin_field:
    file: lib/Perl/Critic/ProfileCompiler/Action/add_or_append_plugin_field.pm
    version: '0.001000'
  Perl::Critic::ProfileCompiler::Action::add_or_replace_plugin:
    file: lib/Perl/Critic/ProfileCompiler/Action/add_or_replace_plugin.pm
    version: '0.001000'
  Perl::Critic::ProfileCompiler::Action::add_or_replace_plugin_field:
    file: lib/Perl/Critic/ProfileCompiler/Action/add_or_replace_plugin_field.pm
    version: '0.001000'
  Perl::Critic::ProfileCompiler::Action::append_bundle:
    file: lib/Perl/Critic/ProfileCompiler/Action/append_bundle.pm
    version: '0.001000'
  Perl::Critic::ProfileCompiler::Action::remove_plugin:
    file: lib/Perl/Critic/ProfileCompiler/Action/remove_plugin.pm
    version: '0.001000'
  Perl::Critic::ProfileCompiler::Role::Action:
    file: lib/Perl/Critic/ProfileCompiler/Role/Action.pm
    version: '0.001000'
  Perl::Critic::ProfileCompiler::Role::Bundle:
    file: lib/Perl/Critic/ProfileCompiler/Role/Bundle.pm
    version: '0.001000'
  Perl::Critic::ProfileCompiler::Role::Bundle::Simple:
    file: lib/Perl/Critic/ProfileCompiler/Role/Bundle/Simple.pm
    version: '0.001000'
  Perl::Critic::ProfileCompiler::Util:
    file: lib/Perl/Critic/ProfileCompiler/Util.pm
    version: '0.001000'
requires:
  Module::Runtime: '0'
  Moo: '0'
  Moo::Role: '1.000008'
  Scalar::Util: '0'
  Sub::Exporter::Progressive: '0'
  perl: '5.008'
  strict: '0'
  utf8: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/kentfredric/Perl-Critic-ProfileCompiler/issues
  homepage: https://github.com/kentfredric/Perl-Critic-ProfileCompiler
  repository: https://github.com/kentfredric/Perl-Critic-ProfileCompiler.git
version: '0.001000'
x_BuiltWith:
  modules:
    CPAN::Meta: '2.133380'
    CPAN::Meta::Requirements: '2.125'
    Dist::Zilla::Plugin::Authority: '1.006'
    Dist::Zilla::Plugin::AutoPrereqs: '5.012'
    Dist::Zilla::Plugin::ConfirmRelease: '5.012'
    Dist::Zilla::Plugin::EOLTests: '0.02'
    Dist::Zilla::Plugin::Git::Check: '2.019'
    Dist::Zilla::Plugin::Git::Commit: '2.019'
    Dist::Zilla::Plugin::Git::CommitBuild: '2.019'
    Dist::Zilla::Plugin::Git::GatherDir: '2.019'
    Dist::Zilla::Plugin::Git::NextRelease: '0.002010'
    Dist::Zilla::Plugin::Git::NextVersion::Sanitized: '0.001000'
    Dist::Zilla::Plugin::Git::Tag: '2.019'
    Dist::Zilla::Plugin::GithubMeta: '0.42'
    Dist::Zilla::Plugin::License: '5.012'
    Dist::Zilla::Plugin::MakeMaker: '5.012'
    Dist::Zilla::Plugin::Manifest: '5.012'
    Dist::Zilla::Plugin::ManifestSkip: '5.012'
    Dist::Zilla::Plugin::MetaConfig: '5.012'
    Dist::Zilla::Plugin::MetaData::BuiltWith: '0.04000002'
    Dist::Zilla::Plugin::MetaJSON: '5.012'
    Dist::Zilla::Plugin::MetaProvides::Package: '1.15000003'
    Dist::Zilla::Plugin::MetaTests: '5.012'
    Dist::Zilla::Plugin::MetaYAML: '5.012'
    Dist::Zilla::Plugin::MinimumPerl: '1.003'
    Dist::Zilla::Plugin::PkgVersion: '5.012'
    Dist::Zilla::Plugin::PodCoverageTests: '5.012'
    Dist::Zilla::Plugin::PodSyntaxTests: '5.012'
    Dist::Zilla::Plugin::PodWeaver: '4.005'
    Dist::Zilla::Plugin::Prereqs: '5.012'
    Dist::Zilla::Plugin::Prereqs::Recommend::MatchInstalled: '0.001000'
    Dist::Zilla::Plugin::ReadmeAnyFromPod: '0.133360'
    Dist::Zilla::Plugin::ReadmeFromPod: '0.21'
    Dist::Zilla::Plugin::RunExtraTests: '0.016'
    Dist::Zilla::Plugin::Test::CPAN::Changes: '0.008'
    Dist::Zilla::Plugin::Test::Compile::PerFile: '0.001001'
    Dist::Zilla::Plugin::Test::Kwalitee: '2.07'
    Dist::Zilla::Plugin::Test::MinimumVersion: '2.000005'
    Dist::Zilla::Plugin::Test::Perl::Critic: '2.112410'
    Dist::Zilla::Plugin::Test::ReportPrereqs: '0.013'
    Dist::Zilla::Plugin::TestRelease: '5.012'
    Dist::Zilla::Plugin::Twitter: '0.025'
    Dist::Zilla::Plugin::UploadToCPAN: '5.012'
    Dist::Zilla::PluginBundle::Author::KENTNL: '2.012000'
    Dist::Zilla::PluginBundle::Author::KENTNL::Lite: 1.7.2
    ExtUtils::MakeMaker: '6.88'
    File::Spec::Functions: '3.40'
    List::Util: '1.38'
    Module::Runtime: '0.013'
    Moo: '1.004002'
    Moo::Role: '1.004002'
    Pod::Coverage::TrustPod: '0.100003'
    Scalar::Util: '1.38'
    Sub::Exporter::Progressive: '0.001011'
    Test::CPAN::Changes: '0.27'
    Test::CPAN::Meta: '0.23'
    Test::Kwalitee: '1.18'
    Test::More: '1.001002'
    Test::Pod: '1.48'
    Test::Pod::Coverage: '1.08'
    strict: '1.08'
    utf8: '1.13'
    version: '0.9907'
    warnings: '1.21'
  perl:
    original: v5.19.8
    qv: 1
    version:
      - 5
      - 19
      - 8
  perl-config:
    gccversion: 4.7.3
    myarchname: x86_64-linux
    osname: linux
  platform: linux
  uname: 'Linux 3.13.0-gentoo-r1 x86_64 GenuineIntel GNU/Linux'
x_Dist_Zilla:
  perl:
    version: '5.019008'
  plugins:
    -
      class: Dist::Zilla::Plugin::Git::NextVersion::Sanitized
      config:
        Dist::Zilla::Role::Version::Sanitize:
          mantissa: '6'
          normal_form: numify
      name: '@Author::KENTNL/Git::NextVersion::Sanitized'
      version: '0.001000'
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@Author::KENTNL/MetaConfig'
      version: '5.012'
    -
      class: Dist::Zilla::Plugin::GithubMeta
      name: '@Author::KENTNL/GithubMeta'
      version: '0.42'
    -
      class: Dist::Zilla::Plugin::MetaProvides::Package
      config:
        Dist::Zilla::Plugin::MetaProvides::Package:
          finder_objects:
            -
              class: Dist::Zilla::Plugin::FinderCode
              name: '@Author::KENTNL/MetaProvides::Package/AUTOVIV/:InstallModulesPM'
              version: '5.012'
        Dist::Zilla::Role::MetaProvider::Provider:
          inherit_missing: '1'
          inherit_version: '1'
          meta_noindex: '1'
      name: '@Author::KENTNL/MetaProvides::Package'
      version: '1.15000003'
    -
      class: Dist::Zilla::Plugin::MetaData::BuiltWith
      config:
        Dist::Zilla::Plugin::MetaData::BuiltWith:
          _stash_key: x_BuiltWith
          show_config: '1'
          show_uname: '1'
          uname:
            uname_args:
              - -s
              - -o
              - -r
              - -m
              - -i
            uname_call: uname
      name: '@Author::KENTNL/MetaData::BuiltWith'
      version: '0.04000002'
    -
      class: Dist::Zilla::Plugin::Git::GatherDir
      name: '@Author::KENTNL/Git::GatherDir'
      version: '2.019'
    -
      class: Dist::Zilla::Plugin::License
      name: '@Author::KENTNL/License'
      version: '5.012'
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: '@Author::KENTNL/MetaJSON'
      version: '5.012'
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@Author::KENTNL/MetaYAML'
      version: '5.012'
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@Author::KENTNL/Manifest'
      version: '5.012'
    -
      class: Dist::Zilla::Plugin::MetaTests
      name: '@Author::KENTNL/MetaTests'
      version: '5.012'
    -
      class: Dist::Zilla::Plugin::PodCoverageTests
      name: '@Author::KENTNL/PodCoverageTests'
      version: '5.012'
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: '@Author::KENTNL/PodSyntaxTests'
      version: '5.012'
    -
      class: Dist::Zilla::Plugin::Test::ReportPrereqs
      name: '@Author::KENTNL/Test::ReportPrereqs'
      version: '0.013'
    -
      class: Dist::Zilla::Plugin::Test::Kwalitee
      name: '@Author::KENTNL/Test::Kwalitee'
      version: '2.07'
    -
      class: Dist::Zilla::Plugin::EOLTests
      name: '@Author::KENTNL/EOLTests'
      version: '0.02'
    -
      class: Dist::Zilla::Plugin::Test::MinimumVersion
      name: '@Author::KENTNL/Test::MinimumVersion'
      version: '2.000005'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: '@Author::KENTNL/Test::Compile::PerFile/AUTOVIV/:InstallModulesPM'
      version: '5.012'
    -
      class: Dist::Zilla::Plugin::Test::Compile::PerFile
      config:
        Dist::Zilla::Plugin::Test::Compile::PerFile:
          file:
            - lib/Perl/Critic/ProfileCompiler.pm
            - lib/Perl/Critic/ProfileCompiler/Action/add_or_append_plugin_field.pm
            - lib/Perl/Critic/ProfileCompiler/Action/add_or_replace_plugin.pm
            - lib/Perl/Critic/ProfileCompiler/Action/add_or_replace_plugin_field.pm
            - lib/Perl/Critic/ProfileCompiler/Action/append_bundle.pm
            - lib/Perl/Critic/ProfileCompiler/Action/remove_plugin.pm
            - lib/Perl/Critic/ProfileCompiler/Role/Action.pm
            - lib/Perl/Critic/ProfileCompiler/Role/Bundle.pm
            - lib/Perl/Critic/ProfileCompiler/Role/Bundle/Simple.pm
            - lib/Perl/Critic/ProfileCompiler/Util.pm
          path_translator: base64_filter
          prefix: t/00-compile
          skip: []
          test_template: 01-basic.t.tpl
          xt_mode: ~
      name: '@Author::KENTNL/Test::Compile::PerFile'
      version: '0.001001'
    -
      class: Dist::Zilla::Plugin::Test::Perl::Critic
      name: '@Author::KENTNL/Test::Perl::Critic'
      version: '2.112410'
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@Author::KENTNL/ManifestSkip'
      version: '5.012'
    -
      class: Dist::Zilla::Plugin::PkgVersion
      name: '@Author::KENTNL/PkgVersion'
      version: '5.012'
    -
      class: Dist::Zilla::Plugin::PodWeaver
      config:
        Dist::Zilla::Plugin::PodWeaver:
          finder:
            - ':InstallModules'
            - ':ExecFiles'
          plugins:
            -
              class: Pod::Weaver::Plugin::EnsurePod5
              name: '@CorePrep/EnsurePod5'
              version: '4.006'
            -
              class: Pod::Weaver::Plugin::H1Nester
              name: '@CorePrep/H1Nester'
              version: '4.006'
            -
              class: Pod::Weaver::Plugin::SingleEncoding
              name: -SingleEncoding
              version: '4.006'
            -
              class: Pod::Weaver::Section::Name
              name: Name
              version: '4.006'
            -
              class: Pod::Weaver::Section::Version
              name: Version
              version: '4.006'
            -
              class: Pod::Weaver::Section::Region
              name: prelude
              version: '4.006'
            -
              class: Pod::Weaver::Section::Generic
              name: SYNOPSIS
              version: '4.006'
            -
              class: Pod::Weaver::Section::Generic
              name: DESCRIPTION
              version: '4.006'
            -
              class: Pod::Weaver::Section::Generic
              name: OVERVIEW
              version: '4.006'
            -
              class: Pod::Weaver::Section::Collect
              name: METHODS
              version: '4.006'
            -
              class: Pod::Weaver::Section::Collect
              name: ATTRIBUTES
              version: '4.006'
            -
              class: Pod::Weaver::Section::Collect
              name: PRIVATE_ATTRIBUTES
              version: '4.006'
            -
              class: Pod::Weaver::Section::Collect
              name: PRIVATE_METHODS
              version: '4.006'
            -
              class: Pod::Weaver::Section::Leftovers
              name: Leftovers
              version: '4.006'
            -
              class: Pod::Weaver::Section::Region
              name: postlude
              version: '4.006'
            -
              class: Pod::Weaver::Section::Authors
              name: Authors
              version: '4.006'
            -
              class: Pod::Weaver::Section::Legal
              name: Legal
              version: '4.006'
      name: '@Author::KENTNL/PodWeaver'
      version: '4.005'
    -
      class: Dist::Zilla::Plugin::Git::NextRelease
      name: '@Author::KENTNL/Git::NextRelease'
      version: '0.002010'
    -
      class: Dist::Zilla::Plugin::AutoPrereqs
      name: '@Author::KENTNL/AutoPrereqs'
      version: '5.012'
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: develop
          type: suggests
      name: '@Author::KENTNL/BundleDevelSuggests'
      version: '5.012'
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: develop
          type: requires
      name: '@Author::KENTNL/BundleDevelRequires'
      version: '5.012'
    -
      class: Dist::Zilla::Plugin::MinimumPerl
      name: '@Author::KENTNL/MinimumPerl'
      version: '1.003'
    -
      class: Dist::Zilla::Plugin::Authority
      name: '@Author::KENTNL/Authority'
      version: '1.006'
    -
      class: Dist::Zilla::Plugin::MakeMaker
      name: '@Author::KENTNL/MakeMaker'
      version: '5.012'
    -
      class: Dist::Zilla::Plugin::ReadmeFromPod
      name: '@Author::KENTNL/ReadmeFromPod'
      version: '0.21'
    -
      class: Dist::Zilla::Plugin::ReadmeAnyFromPod
      name: '@Author::KENTNL/ReadmeAnyFromPod'
      version: '0.133360'
    -
      class: Dist::Zilla::Plugin::Test::CPAN::Changes
      name: '@Author::KENTNL/Test::CPAN::Changes'
      version: '0.008'
    -
      class: Dist::Zilla::Plugin::RunExtraTests
      name: '@Author::KENTNL/RunExtraTests'
      version: '0.016'
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: '@Author::KENTNL/TestRelease'
      version: '5.012'
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: '@Author::KENTNL/ConfirmRelease'
      version: '5.012'
    -
      class: Dist::Zilla::Plugin::Git::Check
      name: '@Author::KENTNL/Git::Check'
      version: '2.019'
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: '@Author::KENTNL/tag_master'
      version: '2.019'
    -
      class: Dist::Zilla::Plugin::Git::Commit
      name: '@Author::KENTNL/Git::Commit'
      version: '2.019'
    -
      class: Dist::Zilla::Plugin::Git::CommitBuild
      name: '@Author::KENTNL/Git::CommitBuild'
      version: '2.019'
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: '@Author::KENTNL/tag_release'
      version: '2.019'
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@Author::KENTNL/UploadToCPAN'
      version: '5.012'
    -
      class: Dist::Zilla::Plugin::Twitter
      name: '@Author::KENTNL/Twitter'
      version: '0.025'
    -
      class: Dist::Zilla::Plugin::Prereqs::Recommend::MatchInstalled
      config:
        Dist::Zilla::Plugin::Prereqs::Recommend::MatchInstalled:
          applyto_map:
            - 'build.requires = build.recommends'
            - 'test.requires = test.recommends'
            - 'runtime.requires = runtime.recommends'
            - 'configure.requires = configure.recommends'
            - 'develop.requires = develop.recommends'
          applyto_phase:
            - build
            - test
            - runtime
            - configure
            - develop
          modules:
            - ExtUtils::MakeMaker
            - Test::More
      name: '@Author::KENTNL/Prereqs::Recommend::MatchInstalled'
      version: '0.001000'
    -
      class: Dist::Zilla::Plugin::Prereqs::Recommend::MatchInstalled
      config:
        Dist::Zilla::Plugin::Prereqs::Recommend::MatchInstalled:
          applyto_map:
            - 'develop.requires = develop.requires'
          applyto_phase:
            - develop
          modules:
            - Dist::Zilla::PluginBundle::Author::KENTNL
      name: '@Author::KENTNL/always_latest_develop_bundle'
      version: '0.001000'
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: develop
          type: requires
      name: '@Author::KENTNL/::Role::BundleDeps'
      version: '5.012'
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: runtime
          type: requires
      name: Prereqs
      version: '5.012'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: '5.012'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':IncModules'
      version: '5.012'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: '5.012'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: '5.012'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: '5.012'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':MainModule'
      version: '5.012'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':AllFiles'
      version: '5.012'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':NoFiles'
      version: '5.012'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: '@Author::KENTNL/MetaProvides::Package/AUTOVIV/:InstallModulesPM'
      version: '5.012'
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: '0'
    version: '5.012'
x_authority: cpan:KENTNL
